### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 1.33 GiB

### ISSUE THREAD

**Issue by bigboss97** [iPERDance/iPERCore#57]
I'm getting "CUDA out of memory". I googled that and it has suggested to send smaller batchs to CUDA.
Where in the scripts can I change?
```
C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\torch\nn\functional.py:3384: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
  1%|▊                                                                                 | 1/100 [00:10<18:06, 10.97s/it]Process Personalizer_['0']:
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\bin\ipercore-main\iPERCore\services\personalization.py", line 119, in run
    self._model.set_input(train_batch, self._device)
  File "e:\bin\ipercore-main\iPERCore\tools\trainers\lwg_trainer.py", line 676, in set_input
    links_ids=links_ids, offsets=offsets, temporal=self._opt.temporal)
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "e:\bin\ipercore-main\iPERCore\tools\trainers\base.py", line 126, in forward
    links_ids=links_ids, offsets=offsets, temporal=temporal
  File "e:\bin\ipercore-main\iPERCore\models\flowcomposition.py", line 726, in forward
    uv_img, input_G_bg, input_G_src = self.process_source(src_img, src_info, primary_ids=primary_ids)
  File "e:\bin\ipercore-main\iPERCore\models\flowcomposition.py", line 479, in process_source
    src_info, erode_ks=0, dilate_ks=0)
  File "e:\bin\ipercore-main\iPERCore\models\flowcomposition.py", line 374, in make_morph_image
    weights, nn_pts, ids = self.cal_top_k_ids(uncertain_points, boundaries_points)
  File "e:\bin\ipercore-main\iPERCore\models\flowcomposition.py", line 280, in cal_top_k_ids
    dists = torch.sum((u_pts - b_pts) ** 2, dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 1.33 GiB (GPU 0; 6.00 GiB total capacity; 985.81 MiB already allocated; 1.11 GiB free; 3.55 GiB reserved in total by PyTorch)
```

**Comment by piaozhx** [comment]
**Notice that `imags_size=512` need at least 9.8GB GPU memory.** if you are using a middle-level GPU(e.g. RTX 2060), you should change the `image_size` to 384 or 256. The following table can be used as a reference:

| image_size | preprocess | personalize | run_imitator | recommended gpu                    |
| ---------- | ---------- | ----------- | ------------ | ---------------------------------- |
| 256x256    | 3.1 GB     | 4.3 GB      | 1.1 GB       | RTX 2060 / RTX 2070                |
| 384x384    | 3.1 GB     | 7.9 GB      | 1.5 GB       | GTX 1080Ti / RTX 2080Ti / Titan Xp |
| 512x512    | 3.1 GB     | 9.8 GB      | 2 GB         | GTX 1080Ti / RTX 2080Ti / Titan Xp |
| 1024x1024  | 3.1 GB     | 20 GB       | -            | RTX Titan / P40 / V100 32G         |

**Comment by bigboss97** [comment]
Super, it works now, thanks!
I'm using GTX1060 and 384 image size.
